//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Trazabilidad.WSIntegrator {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSDigiturnoSoap", Namespace="http://190.144.73.250:9090/")]
    public partial class WSDigiturno : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GenerateTurnOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPatientOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPatientAppointmentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdatePaymentAppointmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAppointmentsForProgramsOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecieveTurnOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTimeDistributionOperationCompleted;
        
        private System.Threading.SendOrPostCallback CallPatientOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateInspiraObjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateProductsByRateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateCostcentersByUnitOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateRatesByAgreementOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateDiscountsByRateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTodayPatientsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSDigiturno() {
            this.Url = global::Trazabilidad.Properties.Settings.Default.Trazabilidad_WSIntegrator_WSDigiturno;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GenerateTurnCompletedEventHandler GenerateTurnCompleted;
        
        /// <remarks/>
        public event GetPatientCompletedEventHandler GetPatientCompleted;
        
        /// <remarks/>
        public event GetPatientAppointmentsCompletedEventHandler GetPatientAppointmentsCompleted;
        
        /// <remarks/>
        public event UpdatePaymentAppointmentCompletedEventHandler UpdatePaymentAppointmentCompleted;
        
        /// <remarks/>
        public event GetAppointmentsForProgramsCompletedEventHandler GetAppointmentsForProgramsCompleted;
        
        /// <remarks/>
        public event RecieveTurnCompletedEventHandler RecieveTurnCompleted;
        
        /// <remarks/>
        public event GetTimeDistributionCompletedEventHandler GetTimeDistributionCompleted;
        
        /// <remarks/>
        public event CallPatientCompletedEventHandler CallPatientCompleted;
        
        /// <remarks/>
        public event UpdateInspiraObjectCompletedEventHandler UpdateInspiraObjectCompleted;
        
        /// <remarks/>
        public event UpdateProductsByRateCompletedEventHandler UpdateProductsByRateCompleted;
        
        /// <remarks/>
        public event UpdateCostcentersByUnitCompletedEventHandler UpdateCostcentersByUnitCompleted;
        
        /// <remarks/>
        public event UpdateRatesByAgreementCompletedEventHandler UpdateRatesByAgreementCompleted;
        
        /// <remarks/>
        public event UpdateDiscountsByRateCompletedEventHandler UpdateDiscountsByRateCompleted;
        
        /// <remarks/>
        public event UpdateAccountCompletedEventHandler UpdateAccountCompleted;
        
        /// <remarks/>
        public event GetTodayPatientsCompletedEventHandler GetTodayPatientsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://190.144.73.250:9090/GenerateTurn", RequestNamespace="http://190.144.73.250:9090/", ResponseNamespace="http://190.144.73.250:9090/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GenerateTurn(string oRequest) {
            object[] results = this.Invoke("GenerateTurn", new object[] {
                        oRequest});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GenerateTurnAsync(string oRequest) {
            this.GenerateTurnAsync(oRequest, null);
        }
        
        /// <remarks/>
        public void GenerateTurnAsync(string oRequest, object userState) {
            if ((this.GenerateTurnOperationCompleted == null)) {
                this.GenerateTurnOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerateTurnOperationCompleted);
            }
            this.InvokeAsync("GenerateTurn", new object[] {
                        oRequest}, this.GenerateTurnOperationCompleted, userState);
        }
        
        private void OnGenerateTurnOperationCompleted(object arg) {
            if ((this.GenerateTurnCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerateTurnCompleted(this, new GenerateTurnCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://190.144.73.250:9090/GetPatient", RequestNamespace="http://190.144.73.250:9090/", ResponseNamespace="http://190.144.73.250:9090/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Digiturno5 GetPatient(string sdocumenttype, string sdocument, string suser, string spassword) {
            object[] results = this.Invoke("GetPatient", new object[] {
                        sdocumenttype,
                        sdocument,
                        suser,
                        spassword});
            return ((Digiturno5)(results[0]));
        }
        
        /// <remarks/>
        public void GetPatientAsync(string sdocumenttype, string sdocument, string suser, string spassword) {
            this.GetPatientAsync(sdocumenttype, sdocument, suser, spassword, null);
        }
        
        /// <remarks/>
        public void GetPatientAsync(string sdocumenttype, string sdocument, string suser, string spassword, object userState) {
            if ((this.GetPatientOperationCompleted == null)) {
                this.GetPatientOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPatientOperationCompleted);
            }
            this.InvokeAsync("GetPatient", new object[] {
                        sdocumenttype,
                        sdocument,
                        suser,
                        spassword}, this.GetPatientOperationCompleted, userState);
        }
        
        private void OnGetPatientOperationCompleted(object arg) {
            if ((this.GetPatientCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPatientCompleted(this, new GetPatientCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://190.144.73.250:9090/GetPatientAppointments", RequestNamespace="http://190.144.73.250:9090/", ResponseNamespace="http://190.144.73.250:9090/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetPatientAppointments(string sdocumenttype, string sdocument, string suser, string spassword) {
            object[] results = this.Invoke("GetPatientAppointments", new object[] {
                        sdocumenttype,
                        sdocument,
                        suser,
                        spassword});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPatientAppointmentsAsync(string sdocumenttype, string sdocument, string suser, string spassword) {
            this.GetPatientAppointmentsAsync(sdocumenttype, sdocument, suser, spassword, null);
        }
        
        /// <remarks/>
        public void GetPatientAppointmentsAsync(string sdocumenttype, string sdocument, string suser, string spassword, object userState) {
            if ((this.GetPatientAppointmentsOperationCompleted == null)) {
                this.GetPatientAppointmentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPatientAppointmentsOperationCompleted);
            }
            this.InvokeAsync("GetPatientAppointments", new object[] {
                        sdocumenttype,
                        sdocument,
                        suser,
                        spassword}, this.GetPatientAppointmentsOperationCompleted, userState);
        }
        
        private void OnGetPatientAppointmentsOperationCompleted(object arg) {
            if ((this.GetPatientAppointmentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPatientAppointmentsCompleted(this, new GetPatientAppointmentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://190.144.73.250:9090/UpdatePaymentAppointment", RequestNamespace="http://190.144.73.250:9090/", ResponseNamespace="http://190.144.73.250:9090/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdatePaymentAppointment(string scode, string sidappointment, string svalue, string suser, string spassword) {
            object[] results = this.Invoke("UpdatePaymentAppointment", new object[] {
                        scode,
                        sidappointment,
                        svalue,
                        suser,
                        spassword});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdatePaymentAppointmentAsync(string scode, string sidappointment, string svalue, string suser, string spassword) {
            this.UpdatePaymentAppointmentAsync(scode, sidappointment, svalue, suser, spassword, null);
        }
        
        /// <remarks/>
        public void UpdatePaymentAppointmentAsync(string scode, string sidappointment, string svalue, string suser, string spassword, object userState) {
            if ((this.UpdatePaymentAppointmentOperationCompleted == null)) {
                this.UpdatePaymentAppointmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdatePaymentAppointmentOperationCompleted);
            }
            this.InvokeAsync("UpdatePaymentAppointment", new object[] {
                        scode,
                        sidappointment,
                        svalue,
                        suser,
                        spassword}, this.UpdatePaymentAppointmentOperationCompleted, userState);
        }
        
        private void OnUpdatePaymentAppointmentOperationCompleted(object arg) {
            if ((this.UpdatePaymentAppointmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdatePaymentAppointmentCompleted(this, new UpdatePaymentAppointmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://190.144.73.250:9090/GetAppointmentsForPrograms", RequestNamespace="http://190.144.73.250:9090/", ResponseNamespace="http://190.144.73.250:9090/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServintePatient[] GetAppointmentsForPrograms(int iyear, int imonth) {
            object[] results = this.Invoke("GetAppointmentsForPrograms", new object[] {
                        iyear,
                        imonth});
            return ((ServintePatient[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAppointmentsForProgramsAsync(int iyear, int imonth) {
            this.GetAppointmentsForProgramsAsync(iyear, imonth, null);
        }
        
        /// <remarks/>
        public void GetAppointmentsForProgramsAsync(int iyear, int imonth, object userState) {
            if ((this.GetAppointmentsForProgramsOperationCompleted == null)) {
                this.GetAppointmentsForProgramsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAppointmentsForProgramsOperationCompleted);
            }
            this.InvokeAsync("GetAppointmentsForPrograms", new object[] {
                        iyear,
                        imonth}, this.GetAppointmentsForProgramsOperationCompleted, userState);
        }
        
        private void OnGetAppointmentsForProgramsOperationCompleted(object arg) {
            if ((this.GetAppointmentsForProgramsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAppointmentsForProgramsCompleted(this, new GetAppointmentsForProgramsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://190.144.73.250:9090/RecieveTurn", RequestNamespace="http://190.144.73.250:9090/", ResponseNamespace="http://190.144.73.250:9090/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result RecieveTurn(string sTurnResult) {
            object[] results = this.Invoke("RecieveTurn", new object[] {
                        sTurnResult});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void RecieveTurnAsync(string sTurnResult) {
            this.RecieveTurnAsync(sTurnResult, null);
        }
        
        /// <remarks/>
        public void RecieveTurnAsync(string sTurnResult, object userState) {
            if ((this.RecieveTurnOperationCompleted == null)) {
                this.RecieveTurnOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecieveTurnOperationCompleted);
            }
            this.InvokeAsync("RecieveTurn", new object[] {
                        sTurnResult}, this.RecieveTurnOperationCompleted, userState);
        }
        
        private void OnRecieveTurnOperationCompleted(object arg) {
            if ((this.RecieveTurnCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecieveTurnCompleted(this, new RecieveTurnCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://190.144.73.250:9090/GetTimeDistribution", RequestNamespace="http://190.144.73.250:9090/", ResponseNamespace="http://190.144.73.250:9090/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Generic[] GetTimeDistribution(string sCost, int iMonth, int iYear) {
            object[] results = this.Invoke("GetTimeDistribution", new object[] {
                        sCost,
                        iMonth,
                        iYear});
            return ((Generic[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTimeDistributionAsync(string sCost, int iMonth, int iYear) {
            this.GetTimeDistributionAsync(sCost, iMonth, iYear, null);
        }
        
        /// <remarks/>
        public void GetTimeDistributionAsync(string sCost, int iMonth, int iYear, object userState) {
            if ((this.GetTimeDistributionOperationCompleted == null)) {
                this.GetTimeDistributionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTimeDistributionOperationCompleted);
            }
            this.InvokeAsync("GetTimeDistribution", new object[] {
                        sCost,
                        iMonth,
                        iYear}, this.GetTimeDistributionOperationCompleted, userState);
        }
        
        private void OnGetTimeDistributionOperationCompleted(object arg) {
            if ((this.GetTimeDistributionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTimeDistributionCompleted(this, new GetTimeDistributionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://190.144.73.250:9090/CallPatient", RequestNamespace="http://190.144.73.250:9090/", ResponseNamespace="http://190.144.73.250:9090/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CallPatient(string sRoom, string sPatient, string sTurn, string sDocumentType, string sDocument, string sIsUpdate, string sFloor) {
            this.Invoke("CallPatient", new object[] {
                        sRoom,
                        sPatient,
                        sTurn,
                        sDocumentType,
                        sDocument,
                        sIsUpdate,
                        sFloor});
        }
        
        /// <remarks/>
        public void CallPatientAsync(string sRoom, string sPatient, string sTurn, string sDocumentType, string sDocument, string sIsUpdate, string sFloor) {
            this.CallPatientAsync(sRoom, sPatient, sTurn, sDocumentType, sDocument, sIsUpdate, sFloor, null);
        }
        
        /// <remarks/>
        public void CallPatientAsync(string sRoom, string sPatient, string sTurn, string sDocumentType, string sDocument, string sIsUpdate, string sFloor, object userState) {
            if ((this.CallPatientOperationCompleted == null)) {
                this.CallPatientOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallPatientOperationCompleted);
            }
            this.InvokeAsync("CallPatient", new object[] {
                        sRoom,
                        sPatient,
                        sTurn,
                        sDocumentType,
                        sDocument,
                        sIsUpdate,
                        sFloor}, this.CallPatientOperationCompleted, userState);
        }
        
        private void OnCallPatientOperationCompleted(object arg) {
            if ((this.CallPatientCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallPatientCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://190.144.73.250:9090/UpdateInspiraObject", RequestNamespace="http://190.144.73.250:9090/", ResponseNamespace="http://190.144.73.250:9090/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateInspiraObject(InspiraTemporal[] linspiratemporal, string sobject) {
            this.Invoke("UpdateInspiraObject", new object[] {
                        linspiratemporal,
                        sobject});
        }
        
        /// <remarks/>
        public void UpdateInspiraObjectAsync(InspiraTemporal[] linspiratemporal, string sobject) {
            this.UpdateInspiraObjectAsync(linspiratemporal, sobject, null);
        }
        
        /// <remarks/>
        public void UpdateInspiraObjectAsync(InspiraTemporal[] linspiratemporal, string sobject, object userState) {
            if ((this.UpdateInspiraObjectOperationCompleted == null)) {
                this.UpdateInspiraObjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateInspiraObjectOperationCompleted);
            }
            this.InvokeAsync("UpdateInspiraObject", new object[] {
                        linspiratemporal,
                        sobject}, this.UpdateInspiraObjectOperationCompleted, userState);
        }
        
        private void OnUpdateInspiraObjectOperationCompleted(object arg) {
            if ((this.UpdateInspiraObjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateInspiraObjectCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://190.144.73.250:9090/UpdateProductsByRate", RequestNamespace="http://190.144.73.250:9090/", ResponseNamespace="http://190.144.73.250:9090/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateProductsByRate(TarifaProducto[] ltarifaProductos) {
            this.Invoke("UpdateProductsByRate", new object[] {
                        ltarifaProductos});
        }
        
        /// <remarks/>
        public void UpdateProductsByRateAsync(TarifaProducto[] ltarifaProductos) {
            this.UpdateProductsByRateAsync(ltarifaProductos, null);
        }
        
        /// <remarks/>
        public void UpdateProductsByRateAsync(TarifaProducto[] ltarifaProductos, object userState) {
            if ((this.UpdateProductsByRateOperationCompleted == null)) {
                this.UpdateProductsByRateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateProductsByRateOperationCompleted);
            }
            this.InvokeAsync("UpdateProductsByRate", new object[] {
                        ltarifaProductos}, this.UpdateProductsByRateOperationCompleted, userState);
        }
        
        private void OnUpdateProductsByRateOperationCompleted(object arg) {
            if ((this.UpdateProductsByRateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateProductsByRateCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://190.144.73.250:9090/UpdateCostcentersByUnit", RequestNamespace="http://190.144.73.250:9090/", ResponseNamespace="http://190.144.73.250:9090/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateCostcentersByUnit(Generic[] lgeneric) {
            this.Invoke("UpdateCostcentersByUnit", new object[] {
                        lgeneric});
        }
        
        /// <remarks/>
        public void UpdateCostcentersByUnitAsync(Generic[] lgeneric) {
            this.UpdateCostcentersByUnitAsync(lgeneric, null);
        }
        
        /// <remarks/>
        public void UpdateCostcentersByUnitAsync(Generic[] lgeneric, object userState) {
            if ((this.UpdateCostcentersByUnitOperationCompleted == null)) {
                this.UpdateCostcentersByUnitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateCostcentersByUnitOperationCompleted);
            }
            this.InvokeAsync("UpdateCostcentersByUnit", new object[] {
                        lgeneric}, this.UpdateCostcentersByUnitOperationCompleted, userState);
        }
        
        private void OnUpdateCostcentersByUnitOperationCompleted(object arg) {
            if ((this.UpdateCostcentersByUnitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCostcentersByUnitCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://190.144.73.250:9090/UpdateRatesByAgreement", RequestNamespace="http://190.144.73.250:9090/", ResponseNamespace="http://190.144.73.250:9090/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateRatesByAgreement(InspiraTemporal[] lTarifaEmpresa) {
            this.Invoke("UpdateRatesByAgreement", new object[] {
                        lTarifaEmpresa});
        }
        
        /// <remarks/>
        public void UpdateRatesByAgreementAsync(InspiraTemporal[] lTarifaEmpresa) {
            this.UpdateRatesByAgreementAsync(lTarifaEmpresa, null);
        }
        
        /// <remarks/>
        public void UpdateRatesByAgreementAsync(InspiraTemporal[] lTarifaEmpresa, object userState) {
            if ((this.UpdateRatesByAgreementOperationCompleted == null)) {
                this.UpdateRatesByAgreementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateRatesByAgreementOperationCompleted);
            }
            this.InvokeAsync("UpdateRatesByAgreement", new object[] {
                        lTarifaEmpresa}, this.UpdateRatesByAgreementOperationCompleted, userState);
        }
        
        private void OnUpdateRatesByAgreementOperationCompleted(object arg) {
            if ((this.UpdateRatesByAgreementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateRatesByAgreementCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://190.144.73.250:9090/UpdateDiscountsByRate", RequestNamespace="http://190.144.73.250:9090/", ResponseNamespace="http://190.144.73.250:9090/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateDiscountsByRate(InspiraTemporal[] ldescuentoTarifa) {
            this.Invoke("UpdateDiscountsByRate", new object[] {
                        ldescuentoTarifa});
        }
        
        /// <remarks/>
        public void UpdateDiscountsByRateAsync(InspiraTemporal[] ldescuentoTarifa) {
            this.UpdateDiscountsByRateAsync(ldescuentoTarifa, null);
        }
        
        /// <remarks/>
        public void UpdateDiscountsByRateAsync(InspiraTemporal[] ldescuentoTarifa, object userState) {
            if ((this.UpdateDiscountsByRateOperationCompleted == null)) {
                this.UpdateDiscountsByRateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateDiscountsByRateOperationCompleted);
            }
            this.InvokeAsync("UpdateDiscountsByRate", new object[] {
                        ldescuentoTarifa}, this.UpdateDiscountsByRateOperationCompleted, userState);
        }
        
        private void OnUpdateDiscountsByRateOperationCompleted(object arg) {
            if ((this.UpdateDiscountsByRateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateDiscountsByRateCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://190.144.73.250:9090/UpdateAccount", RequestNamespace="http://190.144.73.250:9090/", ResponseNamespace="http://190.144.73.250:9090/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateAccount(string sDocument, string sDocumentType, string[] aResponse) {
            this.Invoke("UpdateAccount", new object[] {
                        sDocument,
                        sDocumentType,
                        aResponse});
        }
        
        /// <remarks/>
        public void UpdateAccountAsync(string sDocument, string sDocumentType, string[] aResponse) {
            this.UpdateAccountAsync(sDocument, sDocumentType, aResponse, null);
        }
        
        /// <remarks/>
        public void UpdateAccountAsync(string sDocument, string sDocumentType, string[] aResponse, object userState) {
            if ((this.UpdateAccountOperationCompleted == null)) {
                this.UpdateAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateAccountOperationCompleted);
            }
            this.InvokeAsync("UpdateAccount", new object[] {
                        sDocument,
                        sDocumentType,
                        aResponse}, this.UpdateAccountOperationCompleted, userState);
        }
        
        private void OnUpdateAccountOperationCompleted(object arg) {
            if ((this.UpdateAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateAccountCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://190.144.73.250:9090/GetTodayPatients", RequestNamespace="http://190.144.73.250:9090/", ResponseNamespace="http://190.144.73.250:9090/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetTodayPatients(string sPatients) {
            object[] results = this.Invoke("GetTodayPatients", new object[] {
                        sPatients});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTodayPatientsAsync(string sPatients) {
            this.GetTodayPatientsAsync(sPatients, null);
        }
        
        /// <remarks/>
        public void GetTodayPatientsAsync(string sPatients, object userState) {
            if ((this.GetTodayPatientsOperationCompleted == null)) {
                this.GetTodayPatientsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTodayPatientsOperationCompleted);
            }
            this.InvokeAsync("GetTodayPatients", new object[] {
                        sPatients}, this.GetTodayPatientsOperationCompleted, userState);
        }
        
        private void OnGetTodayPatientsOperationCompleted(object arg) {
            if ((this.GetTodayPatientsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTodayPatientsCompleted(this, new GetTodayPatientsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://190.144.73.250:9090/")]
    public partial class Digiturno5 {
        
        private PatientCiel oPatientField;
        
        private Result oResultField;
        
        /// <remarks/>
        public PatientCiel oPatient {
            get {
                return this.oPatientField;
            }
            set {
                this.oPatientField = value;
            }
        }
        
        /// <remarks/>
        public Result oResult {
            get {
                return this.oResultField;
            }
            set {
                this.oResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://190.144.73.250:9090/")]
    public partial class PatientCiel {
        
        private int iplanField;
        
        private int iunitField;
        
        private int iattendanceField;
        
        private string sfirstnameField;
        
        private string ssecondnameField;
        
        private string sfirstsurnameField;
        
        private string ssecondsurnameField;
        
        /// <remarks/>
        public int iplan {
            get {
                return this.iplanField;
            }
            set {
                this.iplanField = value;
            }
        }
        
        /// <remarks/>
        public int iunit {
            get {
                return this.iunitField;
            }
            set {
                this.iunitField = value;
            }
        }
        
        /// <remarks/>
        public int iattendance {
            get {
                return this.iattendanceField;
            }
            set {
                this.iattendanceField = value;
            }
        }
        
        /// <remarks/>
        public string sfirstname {
            get {
                return this.sfirstnameField;
            }
            set {
                this.sfirstnameField = value;
            }
        }
        
        /// <remarks/>
        public string ssecondname {
            get {
                return this.ssecondnameField;
            }
            set {
                this.ssecondnameField = value;
            }
        }
        
        /// <remarks/>
        public string sfirstsurname {
            get {
                return this.sfirstsurnameField;
            }
            set {
                this.sfirstsurnameField = value;
            }
        }
        
        /// <remarks/>
        public string ssecondsurname {
            get {
                return this.ssecondsurnameField;
            }
            set {
                this.ssecondsurnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://190.144.73.250:9090/")]
    public partial class TarifaProducto {
        
        private string sproductoField;
        
        private string starifaField;
        
        private string sconceptoField;
        
        private string scentroField;
        
        private System.DateTime dfechaField;
        
        private int ivalorField;
        
        private int isincronizadoField;
        
        private int iedicionField;
        
        private int iidField;
        
        /// <remarks/>
        public string sproducto {
            get {
                return this.sproductoField;
            }
            set {
                this.sproductoField = value;
            }
        }
        
        /// <remarks/>
        public string starifa {
            get {
                return this.starifaField;
            }
            set {
                this.starifaField = value;
            }
        }
        
        /// <remarks/>
        public string sconcepto {
            get {
                return this.sconceptoField;
            }
            set {
                this.sconceptoField = value;
            }
        }
        
        /// <remarks/>
        public string scentro {
            get {
                return this.scentroField;
            }
            set {
                this.scentroField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dfecha {
            get {
                return this.dfechaField;
            }
            set {
                this.dfechaField = value;
            }
        }
        
        /// <remarks/>
        public int ivalor {
            get {
                return this.ivalorField;
            }
            set {
                this.ivalorField = value;
            }
        }
        
        /// <remarks/>
        public int isincronizado {
            get {
                return this.isincronizadoField;
            }
            set {
                this.isincronizadoField = value;
            }
        }
        
        /// <remarks/>
        public int iedicion {
            get {
                return this.iedicionField;
            }
            set {
                this.iedicionField = value;
            }
        }
        
        /// <remarks/>
        public int iid {
            get {
                return this.iidField;
            }
            set {
                this.iidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://190.144.73.250:9090/")]
    public partial class InspiraTemporal {
        
        private long lconsecutivoField;
        
        private string scodField;
        
        private string snombreField;
        
        private string sparametro1Field;
        
        private string sparametro2Field;
        
        private string stablaField;
        
        private int iparametro3Field;
        
        private int iidField;
        
        private char cactivoField;
        
        private int isincronizadoField;
        
        private string santeriorField;
        
        private int iedicionField;
        
        private System.DateTime dfechaField;
        
        private string soperacionField;
        
        /// <remarks/>
        public long lconsecutivo {
            get {
                return this.lconsecutivoField;
            }
            set {
                this.lconsecutivoField = value;
            }
        }
        
        /// <remarks/>
        public string scod {
            get {
                return this.scodField;
            }
            set {
                this.scodField = value;
            }
        }
        
        /// <remarks/>
        public string snombre {
            get {
                return this.snombreField;
            }
            set {
                this.snombreField = value;
            }
        }
        
        /// <remarks/>
        public string sparametro1 {
            get {
                return this.sparametro1Field;
            }
            set {
                this.sparametro1Field = value;
            }
        }
        
        /// <remarks/>
        public string sparametro2 {
            get {
                return this.sparametro2Field;
            }
            set {
                this.sparametro2Field = value;
            }
        }
        
        /// <remarks/>
        public string stabla {
            get {
                return this.stablaField;
            }
            set {
                this.stablaField = value;
            }
        }
        
        /// <remarks/>
        public int iparametro3 {
            get {
                return this.iparametro3Field;
            }
            set {
                this.iparametro3Field = value;
            }
        }
        
        /// <remarks/>
        public int iid {
            get {
                return this.iidField;
            }
            set {
                this.iidField = value;
            }
        }
        
        /// <remarks/>
        public char cactivo {
            get {
                return this.cactivoField;
            }
            set {
                this.cactivoField = value;
            }
        }
        
        /// <remarks/>
        public int isincronizado {
            get {
                return this.isincronizadoField;
            }
            set {
                this.isincronizadoField = value;
            }
        }
        
        /// <remarks/>
        public string santerior {
            get {
                return this.santeriorField;
            }
            set {
                this.santeriorField = value;
            }
        }
        
        /// <remarks/>
        public int iedicion {
            get {
                return this.iedicionField;
            }
            set {
                this.iedicionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dfecha {
            get {
                return this.dfechaField;
            }
            set {
                this.dfechaField = value;
            }
        }
        
        /// <remarks/>
        public string soperacion {
            get {
                return this.soperacionField;
            }
            set {
                this.soperacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://190.144.73.250:9090/")]
    public partial class Generic {
        
        private int iidField;
        
        private string snameField;
        
        private string scodeField;
        
        private string sfilterField;
        
        private System.DateTime dtDateField;
        
        private string sextra1Field;
        
        private double dextra2Field;
        
        /// <remarks/>
        public int iid {
            get {
                return this.iidField;
            }
            set {
                this.iidField = value;
            }
        }
        
        /// <remarks/>
        public string sname {
            get {
                return this.snameField;
            }
            set {
                this.snameField = value;
            }
        }
        
        /// <remarks/>
        public string scode {
            get {
                return this.scodeField;
            }
            set {
                this.scodeField = value;
            }
        }
        
        /// <remarks/>
        public string sfilter {
            get {
                return this.sfilterField;
            }
            set {
                this.sfilterField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dtDate {
            get {
                return this.dtDateField;
            }
            set {
                this.dtDateField = value;
            }
        }
        
        /// <remarks/>
        public string sextra1 {
            get {
                return this.sextra1Field;
            }
            set {
                this.sextra1Field = value;
            }
        }
        
        /// <remarks/>
        public double dextra2 {
            get {
                return this.dextra2Field;
            }
            set {
                this.dextra2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://190.144.73.250:9090/")]
    public partial class ServiceRequest {
        
        private string idCargoField;
        
        private string srateField;
        
        private string sconceptField;
        
        private string scostcenterField;
        
        private string sauthorizationField;
        
        private string sserviceField;
        
        private int iqtyField;
        
        private decimal ivalueField;
        
        private decimal idiscountField;
        
        private bool bbilleableField;
        
        private bool bisprocedureField;
        
        private string sservicenameField;
        
        /// <remarks/>
        public string idCargo {
            get {
                return this.idCargoField;
            }
            set {
                this.idCargoField = value;
            }
        }
        
        /// <remarks/>
        public string srate {
            get {
                return this.srateField;
            }
            set {
                this.srateField = value;
            }
        }
        
        /// <remarks/>
        public string sconcept {
            get {
                return this.sconceptField;
            }
            set {
                this.sconceptField = value;
            }
        }
        
        /// <remarks/>
        public string scostcenter {
            get {
                return this.scostcenterField;
            }
            set {
                this.scostcenterField = value;
            }
        }
        
        /// <remarks/>
        public string sauthorization {
            get {
                return this.sauthorizationField;
            }
            set {
                this.sauthorizationField = value;
            }
        }
        
        /// <remarks/>
        public string sservice {
            get {
                return this.sserviceField;
            }
            set {
                this.sserviceField = value;
            }
        }
        
        /// <remarks/>
        public int iqty {
            get {
                return this.iqtyField;
            }
            set {
                this.iqtyField = value;
            }
        }
        
        /// <remarks/>
        public decimal ivalue {
            get {
                return this.ivalueField;
            }
            set {
                this.ivalueField = value;
            }
        }
        
        /// <remarks/>
        public decimal idiscount {
            get {
                return this.idiscountField;
            }
            set {
                this.idiscountField = value;
            }
        }
        
        /// <remarks/>
        public bool bbilleable {
            get {
                return this.bbilleableField;
            }
            set {
                this.bbilleableField = value;
            }
        }
        
        /// <remarks/>
        public bool bisprocedure {
            get {
                return this.bisprocedureField;
            }
            set {
                this.bisprocedureField = value;
            }
        }
        
        /// <remarks/>
        public string sservicename {
            get {
                return this.sservicenameField;
            }
            set {
                this.sservicenameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://190.144.73.250:9090/")]
    public partial class InspiraCita {
        
        private string sappointmentField;
        
        private int ientryField;
        
        private string sattentiontypeField;
        
        private string sservicetypeField;
        
        private string sagreementtypeField;
        
        private string scie10Field;
        
        private string sservicegroupField;
        
        private string sagreementField;
        
        private string sagreementnameField;
        
        private string sratenameField;
        
        private string sunitField;
        
        private string sthirdField;
        
        private string stemplateField;
        
        private string scostcenterField;
        
        private string srateField;
        
        private System.DateTime ddateField;
        
        private string sauthorizationField;
        
        private string splanField;
        
        private ServiceRequest[] lservicesField;
        
        private string suserField;
        
        private string snameField;
        
        /// <remarks/>
        public string sappointment {
            get {
                return this.sappointmentField;
            }
            set {
                this.sappointmentField = value;
            }
        }
        
        /// <remarks/>
        public int ientry {
            get {
                return this.ientryField;
            }
            set {
                this.ientryField = value;
            }
        }
        
        /// <remarks/>
        public string sattentiontype {
            get {
                return this.sattentiontypeField;
            }
            set {
                this.sattentiontypeField = value;
            }
        }
        
        /// <remarks/>
        public string sservicetype {
            get {
                return this.sservicetypeField;
            }
            set {
                this.sservicetypeField = value;
            }
        }
        
        /// <remarks/>
        public string sagreementtype {
            get {
                return this.sagreementtypeField;
            }
            set {
                this.sagreementtypeField = value;
            }
        }
        
        /// <remarks/>
        public string scie10 {
            get {
                return this.scie10Field;
            }
            set {
                this.scie10Field = value;
            }
        }
        
        /// <remarks/>
        public string sservicegroup {
            get {
                return this.sservicegroupField;
            }
            set {
                this.sservicegroupField = value;
            }
        }
        
        /// <remarks/>
        public string sagreement {
            get {
                return this.sagreementField;
            }
            set {
                this.sagreementField = value;
            }
        }
        
        /// <remarks/>
        public string sagreementname {
            get {
                return this.sagreementnameField;
            }
            set {
                this.sagreementnameField = value;
            }
        }
        
        /// <remarks/>
        public string sratename {
            get {
                return this.sratenameField;
            }
            set {
                this.sratenameField = value;
            }
        }
        
        /// <remarks/>
        public string sunit {
            get {
                return this.sunitField;
            }
            set {
                this.sunitField = value;
            }
        }
        
        /// <remarks/>
        public string sthird {
            get {
                return this.sthirdField;
            }
            set {
                this.sthirdField = value;
            }
        }
        
        /// <remarks/>
        public string stemplate {
            get {
                return this.stemplateField;
            }
            set {
                this.stemplateField = value;
            }
        }
        
        /// <remarks/>
        public string scostcenter {
            get {
                return this.scostcenterField;
            }
            set {
                this.scostcenterField = value;
            }
        }
        
        /// <remarks/>
        public string srate {
            get {
                return this.srateField;
            }
            set {
                this.srateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ddate {
            get {
                return this.ddateField;
            }
            set {
                this.ddateField = value;
            }
        }
        
        /// <remarks/>
        public string sauthorization {
            get {
                return this.sauthorizationField;
            }
            set {
                this.sauthorizationField = value;
            }
        }
        
        /// <remarks/>
        public string splan {
            get {
                return this.splanField;
            }
            set {
                this.splanField = value;
            }
        }
        
        /// <remarks/>
        public ServiceRequest[] lservices {
            get {
                return this.lservicesField;
            }
            set {
                this.lservicesField = value;
            }
        }
        
        /// <remarks/>
        public string suser {
            get {
                return this.suserField;
            }
            set {
                this.suserField = value;
            }
        }
        
        /// <remarks/>
        public string sname {
            get {
                return this.snameField;
            }
            set {
                this.snameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://190.144.73.250:9090/")]
    public partial class ServintePatient {
        
        private string idPacienteField;
        
        private string sdocumenttypeField;
        
        private string sdocumentField;
        
        private string sfirstnameField;
        
        private string ssecondnameField;
        
        private string ssurnameField;
        
        private string ssecondsurnameField;
        
        private string sgenderField;
        
        private System.Nullable<System.DateTime> dbirthdateField;
        
        private string sbornplaceField;
        
        private string smaritalstatusField;
        
        private string sphoneField;
        
        private string sneighborhoodField;
        
        private string surbanzoneField;
        
        private string sjobField;
        
        private string saddressField;
        
        private string smailField;
        
        private string safiliationField;
        
        private string slevelField;
        
        private string scellphoneField;
        
        private string snationField;
        
        private string scityField;
        
        private int iidField;
        
        private string scovid1Field;
        
        private string scovid2Field;
        
        private string scitynameField;
        
        private string sagreementcodeField;
        
        private InspiraCita[] lappointmentsField;
        
        /// <remarks/>
        public string idPaciente {
            get {
                return this.idPacienteField;
            }
            set {
                this.idPacienteField = value;
            }
        }
        
        /// <remarks/>
        public string sdocumenttype {
            get {
                return this.sdocumenttypeField;
            }
            set {
                this.sdocumenttypeField = value;
            }
        }
        
        /// <remarks/>
        public string sdocument {
            get {
                return this.sdocumentField;
            }
            set {
                this.sdocumentField = value;
            }
        }
        
        /// <remarks/>
        public string sfirstname {
            get {
                return this.sfirstnameField;
            }
            set {
                this.sfirstnameField = value;
            }
        }
        
        /// <remarks/>
        public string ssecondname {
            get {
                return this.ssecondnameField;
            }
            set {
                this.ssecondnameField = value;
            }
        }
        
        /// <remarks/>
        public string ssurname {
            get {
                return this.ssurnameField;
            }
            set {
                this.ssurnameField = value;
            }
        }
        
        /// <remarks/>
        public string ssecondsurname {
            get {
                return this.ssecondsurnameField;
            }
            set {
                this.ssecondsurnameField = value;
            }
        }
        
        /// <remarks/>
        public string sgender {
            get {
                return this.sgenderField;
            }
            set {
                this.sgenderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dbirthdate {
            get {
                return this.dbirthdateField;
            }
            set {
                this.dbirthdateField = value;
            }
        }
        
        /// <remarks/>
        public string sbornplace {
            get {
                return this.sbornplaceField;
            }
            set {
                this.sbornplaceField = value;
            }
        }
        
        /// <remarks/>
        public string smaritalstatus {
            get {
                return this.smaritalstatusField;
            }
            set {
                this.smaritalstatusField = value;
            }
        }
        
        /// <remarks/>
        public string sphone {
            get {
                return this.sphoneField;
            }
            set {
                this.sphoneField = value;
            }
        }
        
        /// <remarks/>
        public string sneighborhood {
            get {
                return this.sneighborhoodField;
            }
            set {
                this.sneighborhoodField = value;
            }
        }
        
        /// <remarks/>
        public string surbanzone {
            get {
                return this.surbanzoneField;
            }
            set {
                this.surbanzoneField = value;
            }
        }
        
        /// <remarks/>
        public string sjob {
            get {
                return this.sjobField;
            }
            set {
                this.sjobField = value;
            }
        }
        
        /// <remarks/>
        public string saddress {
            get {
                return this.saddressField;
            }
            set {
                this.saddressField = value;
            }
        }
        
        /// <remarks/>
        public string smail {
            get {
                return this.smailField;
            }
            set {
                this.smailField = value;
            }
        }
        
        /// <remarks/>
        public string safiliation {
            get {
                return this.safiliationField;
            }
            set {
                this.safiliationField = value;
            }
        }
        
        /// <remarks/>
        public string slevel {
            get {
                return this.slevelField;
            }
            set {
                this.slevelField = value;
            }
        }
        
        /// <remarks/>
        public string scellphone {
            get {
                return this.scellphoneField;
            }
            set {
                this.scellphoneField = value;
            }
        }
        
        /// <remarks/>
        public string snation {
            get {
                return this.snationField;
            }
            set {
                this.snationField = value;
            }
        }
        
        /// <remarks/>
        public string scity {
            get {
                return this.scityField;
            }
            set {
                this.scityField = value;
            }
        }
        
        /// <remarks/>
        public int iid {
            get {
                return this.iidField;
            }
            set {
                this.iidField = value;
            }
        }
        
        /// <remarks/>
        public string scovid1 {
            get {
                return this.scovid1Field;
            }
            set {
                this.scovid1Field = value;
            }
        }
        
        /// <remarks/>
        public string scovid2 {
            get {
                return this.scovid2Field;
            }
            set {
                this.scovid2Field = value;
            }
        }
        
        /// <remarks/>
        public string scityname {
            get {
                return this.scitynameField;
            }
            set {
                this.scitynameField = value;
            }
        }
        
        /// <remarks/>
        public string sagreementcode {
            get {
                return this.sagreementcodeField;
            }
            set {
                this.sagreementcodeField = value;
            }
        }
        
        /// <remarks/>
        public InspiraCita[] lappointments {
            get {
                return this.lappointmentsField;
            }
            set {
                this.lappointmentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://190.144.73.250:9090/")]
    public partial class Result {
        
        private int iresultField;
        
        private string smessageField;
        
        /// <remarks/>
        public int iresult {
            get {
                return this.iresultField;
            }
            set {
                this.iresultField = value;
            }
        }
        
        /// <remarks/>
        public string smessage {
            get {
                return this.smessageField;
            }
            set {
                this.smessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GenerateTurnCompletedEventHandler(object sender, GenerateTurnCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerateTurnCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerateTurnCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetPatientCompletedEventHandler(object sender, GetPatientCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPatientCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPatientCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Digiturno5 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Digiturno5)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetPatientAppointmentsCompletedEventHandler(object sender, GetPatientAppointmentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPatientAppointmentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPatientAppointmentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void UpdatePaymentAppointmentCompletedEventHandler(object sender, UpdatePaymentAppointmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdatePaymentAppointmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdatePaymentAppointmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetAppointmentsForProgramsCompletedEventHandler(object sender, GetAppointmentsForProgramsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAppointmentsForProgramsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAppointmentsForProgramsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServintePatient[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServintePatient[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void RecieveTurnCompletedEventHandler(object sender, RecieveTurnCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecieveTurnCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecieveTurnCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetTimeDistributionCompletedEventHandler(object sender, GetTimeDistributionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTimeDistributionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTimeDistributionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Generic[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Generic[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CallPatientCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void UpdateInspiraObjectCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void UpdateProductsByRateCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void UpdateCostcentersByUnitCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void UpdateRatesByAgreementCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void UpdateDiscountsByRateCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void UpdateAccountCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetTodayPatientsCompletedEventHandler(object sender, GetTodayPatientsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTodayPatientsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTodayPatientsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591